buildVariable: true
category:
- SERIF
familyName: Noto Serif Vithkuqi
googleFonts: true
includeSubsets:
- from: Noto Serif
  name: GF_Latin_Core
recipeProvider: noto
sources:
- NotoSerifVithkuqi.glyphs
